apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: p2p-benchmark
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
          - targets: ['p2p-node-service.p2p-benchmark.svc.cluster.local:80']
