name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint.yml

